# dev master deployment test
name: Dev - Upload Zome Backend Application

on:
  push:
    branches: dev_master

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Set up JDK 15

        uses: actions/setup-java@v2

        with:

          java-version: 15

          server-id: github
          distribution: 'adopt'

          settings-path: ${{ github.workspace }}
     # - uses: nanasess/setup-chromedriver@v1
      #  with:
          # Optional: do not specify to match Chrome's version
       #   chromedriver-version: '88.0.4324.96'
      #- run: |
       #   export DISPLAY=:99
        #  chromedriver --url-base=/wd/hub &
         # sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
      - name: Login and Set Temp Test
        run:  mvn test -Dtest="LoginTest"

      - name: Add Property Test
        run: mvn test -Dtest="AddPropertyTest"

      - name: Add Building Test
        run: mvn test -Dtest="AddBuildingTest"

      - name: Add User Test
        run: mvn test -Dtest="AddUser"

#      - name: Build with Maven
#        run: mvn -B package --file pom.xml test
      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
         SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
      - name: Store artifact for distribution
        uses: actions/upload-artifact@v3
        with:
          name: Nodeapp-Build
          path: /home/runner/work/zome-energy-desk/zome-energy-desk/*
      - name: executing remote ssh command using ssh key
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.AWS_DEV_HOST }}
          username: ${{ secrets.AWS_DEV_USER }}
          password: ${{ secrets.AWS_DEV_PASSWORD }}
          port: ${{ secrets.PORT }}
          script: sh deploy.sh
